//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLinqQL.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphLinqQL.ErrorMessages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error occurred within resolve method for field &quot;{0}&quot; on type &quot;{1}&quot;. See server logs for details..
        /// </summary>
        internal static string errorInResolver {
            get {
                return ResourceManager.GetString("errorInResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing argument &quot;{1}&quot; for field &quot;{0}&quot;..
        /// </summary>
        internal static string missingArgument {
            get {
                return ResourceManager.GetString("missingArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operation was found in provided GraphQL document.
        /// </summary>
        internal static string noOperationFound {
            get {
                return ResourceManager.GetString("noOperationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; must not have a selection since type &quot;{1}&quot; has no subfields..
        /// </summary>
        internal static string noSubselectionAllowed {
            get {
                return ResourceManager.GetString("noSubselectionAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse query: {0}.
        /// </summary>
        internal static string parseError {
            get {
                return ResourceManager.GetString("parseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; of type &quot;{1}&quot; must have a selection of subfields. Did you mean &quot;{0} {{ ... }}&quot;?.
        /// </summary>
        internal static string requiredSubselection {
            get {
                return ResourceManager.GetString("requiredSubselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot query field &quot;{0}&quot; on type &quot;{1}&quot;..
        /// </summary>
        internal static string undefinedField {
            get {
                return ResourceManager.GetString("undefinedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error occurred in field &quot;{0}&quot;. See server logs for details..
        /// </summary>
        internal static string unhandledError {
            get {
                return ResourceManager.GetString("unhandledError", resourceCulture);
            }
        }
    }
}
